packages:
  - name: lib32gcc
    replace-with: []

  - name: postgresql
    replace-with: [postgresql, postgresql-contrib]

  - name: composer
    virtual: true
    install:
      -> curl -sS https://getcomposer.org/installer |
          php -- --install-dir=/usr/local/bin --filename=composer

  - name: nodejs
    pre-install:
      - mkdir -p /usr/share/keyrings/
      - curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /usr/share/keyrings/nodesource.gpg
      - echo "deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" > /etc/apt/sources.list.d/nodesource.list
