linters:
  enable:
    - asciicheck
    - bodyclose
    - containedctx
    - decorder
    - dogsled
    - dupl
    - dupword
    - errcheck
    - errname
    - exportloopref
    - forcetypeassert
    - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - goimports
    - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - ireturn
    - lll
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - perfsprint
    - prealloc
    - predeclared
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagalign
    - tagliatelle
    - tenv
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
issues:
  exclude-rules:
    - path: test
      linters:
        - funlen
        - lll
        - dupl
        - gosec
        - scopelint
    - path: internal/app/di
      linters:
        - govet
    - path: internal/app/di/internal/definitions
      linters:
        - funlen
        - revive
        - stylecheck

linters-settings:
  gomnd:
    ignored-numbers:
      - '0600'
      - '0644'
      - '0666'
      - '0755'
      - '2'