version: "2"
linters:
  enable:
    - asciicheck
    - bodyclose
    - containedctx
    - decorder
    - dogsled
    #- dupl
    - dupword
    - err113
    - errname
    - forcetypeassert
    - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gomodguard
    - goprintffuncname
    - gosec
    - ireturn
    - lll
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - nolintlint
    - prealloc
    - predeclared
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - thelper
    - unconvert
    - unparam
    - usestdlibvars
    - whitespace
  settings:
    mnd:
      ignored-numbers:
        - "0600"
        - "0644"
        - "0666"
        - "0755"
        - "2"
    goconst:
      ignore-string-values:
        - "localhost"
        - "127.0.0.1"
        - "windows"
    revive:
      rules:
        - name: var-naming
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: "SA1019"  # Disable deprecated warnings
      - linters:
          - dupl
          - funlen
          - gosec
          - lll
          - scopelint
        path: test
      - linters:
          - govet
        path: internal/app/di
      - linters:
          - funlen
          - revive
          - staticcheck
        path: internal/app/di/internal/definitions
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
